#!/bin/bash
#
# Copyright (C) 2017 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT Patches Mixer.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

CONF=$1
DIR=
MERGE_METHOD=
MERGE_CONFLICTS=
VERBOSE=

if [ -z "$1" ] ; then
	echo "USAGE: $0 config_file" 1>&2
	exit 1
fi

# If config file is not present, abort
if [ ! -f "${CONF}" ] ; then
	echo "Error: \"${CONF}\" is not a valid config file" 1>&2
	exit 1
fi

repo_items_count=0

while read -r line ; do
	if [ -n "$line" ] ; then
		case $line in
			DIR=*)
				if [ -n "${DIR}" ] ; then
					echo "Error: option DIR is provided multiple times in config file \"${CONF}\"" 1>&2
					exit 1
				fi

				DIR="${line#DIR=}"
				;;
			MERGE_METHOD=*)
				if [ -n "${MERGE_METHOD}" ] ; then
					echo "Error: option MERGE_METHOD is provided multiple times in config file \"${CONF}\"" 1>&2
					exit 1
				fi

				MERGE_METHOD="${line#MERGE_METHOD=}"

				case "${MERGE_METHOD}" in
					merge) ;;
					read-tree) ;;
					*)
						echo "Error: unsupported MERGE_METHOD \"${MERGE_METHOD}\" is specified in config file \"${CONF}\"" 1>&2
						exit 1
						;;
				esac
				;;
			MERGE_CONFLICTS=*)
				if [ -n "${MERGE_CONFLICTS}" ] ; then
					echo "Error: option MERGE_CONFLICTS is provided multiple times in config file \"${CONF}\"" 1>&2
					exit 1
				fi

				MERGE_CONFLICTS="${line#MERGE_CONFLICTS=}"
				;;
			VERBOSE=*)
				if [ -n "${VERBOSE}" ] ; then
					echo "Error: option VERBOSE is provided multiple times in config file \"${CONF}\"" 1>&2
					exit 1
				fi

				VERBOSE="${line#VERBOSE=}"
				;;
			REPO=*)
				set -- $(echo $line | sed -e 's:#.*$::')

				if [ -n "$2" ] && [ -n "$3" ] ; then
					eval repo_name_${repo_items_count}="${1#REPO=}"
					eval repo_remote_${repo_items_count}="$2"
					eval repo_branches_count_${repo_items_count}=0
					eval repo_gpg_home_${repo_items_count}=""
					value_index=3

					while [ -n "$(eval echo \$$value_index)" ] ; do
						value=$(eval echo \$$value_index)

						case $value in
							gpg=*)
								eval repo_gpg_home_${repo_items_count}="${value#gpg=}"
								;;
							*)
								eval repo_branch_${repo_items_count}_$(eval echo \${repo_branches_count_${repo_items_count}})="$value"
								eval repo_branches_count_${repo_items_count}=$(expr $(eval echo \$repo_branches_count_${repo_items_count}) + 1)
								;;
						esac

						eval value_index=$(expr $value_index + 1)
					done

					repo_items_count=$(expr ${repo_items_count} + 1)
				fi
				;;
		esac
	fi
done < "${CONF}"

# Check config sanity: make sure that there is no repo with same name
for i in $(seq 0 $(expr ${repo_items_count} - 1)) ; do
	for k in $(seq $(expr $i + 1) $(expr ${repo_items_count} - 1)) ; do
		if [ "$(eval echo \$repo_name_$i)" = "$(eval echo \$repo_name_$k)" ] ; then
			echo "Error: repository name \"$(eval echo \$repo_name_$i)\" is provided multiple times in config file \"${CONF}\"" 1>&2
			exit 1
		fi
	done
done

# Check config sanity: make sure that for every repo every branch is specified only once
for i in $(seq 0 $(expr ${repo_items_count} - 1)) ; do
	for j in $(seq 0 $(expr $(eval echo \${repo_branches_count_$i}) - 1)) ; do
		for k in $(seq $(expr $j + 1) $(expr $(eval echo \${repo_branches_count_$i}) - 1)) ; do
			if [ "$(eval echo $\repo_branch_${i}_${j})" = "$(eval echo $\repo_branch_${i}_${k})" ] ; then
				echo "Error: repository \"$(eval echo \$repo_name_$i)\" specifies branch \"$(eval echo $\repo_branch_${i}_${j})\" multiple times in config file \"${CONF}\"" 1>&2
				exit 1
			fi
		done
	done
done

# If dir is not present, abort
if [ ! -d "${DIR}" ] ; then
	echo "Error: \"${DIR}\" is not a valid directory" 1>&2
	exit 1
fi

if [ -z "${MERGE_METHOD}" ] ; then
	echo "Error: MERGE_METHOD is not specified in config file \"${CONF}\"" 1>&2
	exit 1
fi

cd "${DIR}"
if [ $? -ne 0 ] ; then
	echo "Error: failed to change directory to \"${DIR}\"" 1>&2
	exit 1
fi

if [ "${VERBOSE}" != "1" ] ; then
	exec 11> /dev/null
	exec 12> /dev/null
else
	exec 11>&1
	exec 12>&2
fi


# Initialize git if necessary
if [ ! -d "${DIR}/.git" ] ; then
	echo "Performing initial configuration in the target directory"
	git init 1>&11 2>&12
	git config user.name "dt-patches-mixer" 1>&11 2>&12
	git config user.email "dt-patches-mixer@localhost" 1>&11 2>&12
	git commit --allow-empty -m "Initial commit" 1>&11 2>&12
	git tag restore-tag 1>&11 2>&12
fi

for remote in $(git remote) ; do
	git remote remove "${remote}" 1>&11 2>&12
done

# this is needed in order to remove patches from repos and branches no longer in config file
git reset --hard restore-tag 1>&11 2>&12

if [ $(git branch 2>/dev/null | grep temp_branch | wc -l) -ne 0 ] ; then
	git branch -D temp_branch 1>&11 2>&12
fi

# add all remotes
for i in $(seq 0 $(expr ${repo_items_count} - 1)) ; do
	git remote add "$(eval echo \$repo_name_$i)" "$(eval echo \$repo_remote_$i)" 1>&11 2>&12
	if [ $? -ne 0 ] ; then
		echo "Error: failed to add remote repository $(eval echo \$repo_name_$i) at \"$(eval echo \$repo_remote_$i)\"" 1>&2
		exit 1
	fi

	git fetch "$(eval echo \$repo_name_$i)" 1>&11 2>&12
	if [ $? -ne 0 ] ; then
		echo "Error: failed to fetch repository \"$(eval echo \$repo_name_$i)\"" 1>&2
		exit 1
	fi
done

# now merge in every mentioned branch. If something fails, abort with message
for i in $(seq 0 $(expr ${repo_items_count} - 1)) ; do
	for j in $(seq 0 $(expr $(eval echo \${repo_branches_count_$i}) - 1)) ; do
		if [ -n "$(eval echo \$repo_gpg_home_$i)" ] ; then
			echo "Verifying $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j} | cut -d : -f 1)"

			GNUPGHOME="$(eval echo \$repo_gpg_home_$i)" git verify-commit "$(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j} | cut -d : -f 1)" 1>&11 2>&12
			if [ $? -ne 0 ] ; then
				git checkout master 1>&11 2>&12
				git reset --hard restore-tag 1>&11 2>&12
				git reset --hard last-version 1>&11 2>&12
				echo "Error: verification of $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j} | cut -d : -f 1) failed" 1>&2
				exit 1
			fi
		fi

		echo "Merging $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})"

		case "${MERGE_METHOD}" in
			merge)
				git merge ${MERGE_CONFLICTS} --allow-unrelated-histories "$(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})" -m "Merge in $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})" 1>&11 2>&12
				if [ $? -ne 0 ] ; then
					git merge --abort 1>&11 2>&12
					echo "Error: failed to merge in $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})" 1>&2
					exit 1
				fi
				;;
			read-tree)
				git checkout -b temp_branch restore-tag 1>&11 2>&12

				git read-tree "$(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})" 1>&11 2>&12
				if [ $? -ne 0 ] ; then
					git reset HEAD . 1>&11 2>&12
					git checkout -- . 1>&11 2>&12
					git checkout master 1>&11 2>&12
					echo "Error: failed to merge in $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})" 1>&2
					exit 1
				fi

				git commit -m "Checkout $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})" 1>&11 2>&12
				if [ $? -ne 0 ] ; then
					git reset HEAD . 1>&11 2>&12
					git checkout -- . 1>&11 2>&12
					git checkout master 1>&11 2>&12
					echo "Error: failed to merge in $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})" 1>&2
					exit 1
				fi

				git checkout -- . 1>&11 2>&12
				git checkout master 1>&11 2>&12

				git merge ${MERGE_CONFLICTS} temp_branch -m "Merge in $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})" 1>&11 2>&12
				if [ $? -ne 0 ] ; then
					git merge --abort 1>&11 2>&12
					echo "Error: failed to merge in $(eval echo \$repo_name_$i)/$(eval echo $\repo_branch_${i}_${j})" 1>&2
					exit 1
				fi

				git branch -d temp_branch 1>&11 2>&12
				;;
		esac
	done
done

git tag -f last-version 1>&11 2>&12

echo "Patches successfully mixed"
